### ISSUE TITLE
Ezan Vaktinde yanlisliklar var, dogru okuyamiyor

### ISSUE THREAD

**Issue by natsuepvp** [fbostanci/ezanvakti#10]
Selamun Aleykum arkadaslar,

ben bu bölgede yeni oldugum icin, camimizde ekranda bu uygulama üzere vakitleri göstermek icabiyla yükledim. (caminin logosunu felan kenara koyabilme ihtimali varmis bu uygulamada, yanlissam dogrultun beni lütfen)

simdi, yükledim ama vakitlerde yanlislik var, tarihi sabah namazinda gösteriyor mesela:
![EyGYbab](https://github.com/fbostanci/ezanvakti/assets/86474718/0b69301c-d052-45fd-ab41-7900caf8d405)

Bunda bir cözüm varmi? Resim neyi nasil degistirebilirim? HTML CSS Dosyasi nerede oluyor tam olarak?

**Comment by fbostanci** [comment]
Aleyküm selam merhaba
Kullandığınız sürüm büyük ihtimalle Launchpad depodaki eski sürümdü. Diyanet sitesinde değişiklikler yaptığı için içeriği yanlış alıyor. Depoyu güncelleyemediğim için geç dönüş yaptım kusuruma bakmayın. 24.04 için uygulamanın güncel hali depoda mevcut. 

Evet arayüz arka planına resim eklenebiliyor. Logo değiştirme ayarlarda mevcut değil ayarlardan mevcut logonun gösterimini açıp kapatabiliyorsunuz. Uygulama üzerinde bir iki düzenlemeyle de logo değiştirilebilir.

`ezanvakti --listele`
komutuyla kullanılan dizinleri görebilirsiniz. Root üzerindeki `ezanvakti-gui.css` dosyasını .config/ezanvakti altına kopyalayıp üzerinde değişiklikler yapabilirsiniz. [ezanvakti-gui.css içeriği](https://github.com/fbostanci/ezanvakti/blob/master/data/veriler/ezanvakti-gui.css)
