### ISSUE TITLE
Güncelleme hatası alıyorum

### ISSUE THREAD

**Issue by volkankoc** [fbostanci/ezanvakti#2]
Merhabalar programı kurdum gerekli ayarları yaptım fakat güncelleme hatası alıyorum. Archlinux kullanıyorum
![screenshot from 2018-07-18 10-13-38](https://user-images.githubusercontent.com/22777823/42865780-6380990e-8a73-11e8-8f61-d8038be32149.png)

**Comment by fbostanci** [comment]
Merhaba diyanetin adres ve içerik değişikliklerinden dolayı güncelleme yapılamıyor. Ekteki dosyada güncellenmiş dosyalar mevcut. Neler yapılacağı OKUBENİ dosyasında anlatılıyor. 

Yakın zamanda güncelleme yapacağım.

[ezanvakti-gecici-cozum.tar.gz](https://github.com/fbostanci/ezanvakti/files/2233781/ezanvakti-gecici-cozum.tar.gz)
