### ISSUE TITLE
macOS uyumlu?

### ISSUE THREAD

**Issue by fecub** [fbostanci/ezanvakti#6]
macOS da kullanim mümkün mü acaba?
degilse eger, kolayca uyarlanbilinir mi?

**Comment by fbostanci** [comment]
Mac işletim sistemini hiç kullanmadım. Dışardan bakınca büyük oranda çalışması lazım. 

Zsh geliyormuş öntanımlı shell olarak ama bash da yüklüymüş son sürümlerde.  Sıkıntı çıkaracaklardan ilk aklıma gelen notify-send, yerine çeşitli seçenekler var. cocoadialog, terminal-notifier gibi. Ben daha çok cocoadialog'u inceledim. Uyarlanabilir duruyor hem bildirim hem de konum seçim diyalogları için.  

Arayüz için [qt-gui](https://github.com/fbostanci/ezanvakti-qt-gui) daha mantıklı. YAD kuruluyor mu bulamadım Homebrew de de yok. Ayrıyeten kurulsa bile Qt gibi masaüstü ortamına özel görünüm sunamaz.

Uğraşmak istiyorsanız kaynak kodu indirip gerekli bağımlılıklar (kurulu olması lazım ama `coreutils` paketi gerekebilir.) kurulduktan sonra kaynak kod dizini içerisindeyken 
`bash yerelkur.bash` komutuyla kullanıcı dizinine kurulum yapılabilir. `ezv-devel` adıyla kuruyor.  (qt-gui için PATH üzerinde ezanvakti lazım.) Farklı adlandırma işlemleri yerelkur.bash betiği içerisinde anlatılıyor. Kurulum süreci için ayrıca `make` paketi kurulu olmalı. Başlatıcı betik(ezv-devel)  ev dizini içerisinde oluşacak bin dizininde. PATH üzerinde olmadığı için doğrudan çağrılamaz. 

 Konum bilgilerini ayarlar dosyasına elle girerseniz diyalog işleriyle uğraşmazsınız. Ancak bu kadar yardımcı olabiliyorum.

**Comment by fecub** [comment]
Bilgileriniz icin cok tesekkür ederim. Linux üzerinde severek ve uzun süre kullandigim bir uygulamaydi. Allah razi olsun, cok güzel bir calisma olmus. Isimiz dolaysiyla macOS'a gecmek zorunda kaldik, devamda kullanmak istiyorum. Vaktimin yettigi kadariyla üzerinde arastirmalarimi yapacagim, eger elden gelirse uyarlamayi deneyecegim.

**Comment by fbostanci** [comment]
Merhaba güzel düşünceleriniz için ben de teşekkür ederim. Farklı ortamlara alışması gerçekten zor kaldı ki bizim tarafta dağıtımı değiştirmek bile sıkıcı olabiliyor. İş için olunca da zorlayıcı bir etkisi de cabası. Allah yardımıcınız olsun.

Konumuza dönersek ben biraz eklemeler yaptım. Denemek isterseniz dosyayı da yükledim. Güncelleme işlemi için cocoa diyalogları ekledim. Ülke şehir, ilçe soran ve bildirim veren şekilde. Diğer bölümlere dokunmadım. Eğer bu şekilde cocoa çalışırsa umudumuz var demek.:)

Yapmanız gerekenler:
make ve cocoadialog kurulumu + bağımlılıklar
lib/temel_islevler.bash.in 18. satırda cocoadialog un tam konumu var. Sitesinden alıp ekledim orayı doğrulayın/düzenleyin.
 `bash yerelkur.bash --kur` komutu ile ezanvakti adıyla kullanıcı dizinine kurulum yapacak. Başlatıcı bin dizinine eklenecek.
`ezanvakti --guncelle` komutuyla diyaloglar çalışıyor mu bir de güncelleme bildirimi alıyormusunuz bakın.

[ezanvakti-mac.zip](https://github.com/fbostanci/ezanvakti/files/4583835/ezanvakti-mac.zip)
