### ISSUE TITLE
launchpad groovy release 404 not found hatası

### ISSUE THREAD

**Issue by M-Enes** [fbostanci/ezanvakti#7]
Ubuntu 20.10 üzerinde launchpad için kurulum yapmak istediğimde bu hata ile karşılaştım.
![image](https://user-images.githubusercontent.com/62840889/116902213-89d29e00-ac43-11eb-87c1-42db5f07c68c.png)
Kaynak kod üzerinden kurulum deneyeceğim ama bu sorunu belirtmek istedim. Kolay gelsin. Çok güzel bir projeye benziyor.

**Comment by fbostanci** [comment]
Merhaba, Ubuntu 20.04 sonrası için paketleme yapmadım çünkü Ubuntu tarafında yad güncel değil 0.40'tı galiba son baktığımda. Paketleyicisine de yazdım dönmedi. Launchpad üzerinde de yeni sürümlerini paketleyen yok. Yeni sürüm gerektiren özellikler eklediğim için çeşitli hatalar olacak. Bir diğer sorun da Ubuntu'yu sanal kurup paketleme yapıyordum kurulumu da sildiğimden baştan uğraşmam gerek. 

`Kaynak kod üzerinden kurulum deneyeceğim ama bu sorunu belirtmek istedim. Kolay gelsin. Çok güzel bir projeye benziyor.`

Teşekkür ederim ara ara fırsat buldukça uğraşıyorum. Faydalı oluyorsa ne mutlu bana.

**Comment by M-Enes** [comment]
Ubuntu kullanmayı bıraktım zaten. Çok teşekkür ederim.
