### ISSUE TITLE
Archlinux uygulamayı çalıştırırken hata

### ISSUE THREAD

**Issue by erdemoncel** [fbostanci/ezanvakti#9]
Selamün Aleyküm.

Öncelikle emekleriniz için teşekkürler.

Nacizane  [namaz vakti](https://codeberg.org/erdem/namaz) uygulamasını geliştirmiştik.

Eğer arzu ederseniz uygulamayı deneyebilirsiniz.

Archlinux'ta geliştirdiğiniz uygulamayı yay ile kurup, ezanvakti komutu ile çalıştırmaya çalışınca şu şekilde bir hata veriyor :

```
ezanveri dosyası güncelleniyor...                           [  BAŞARILI  ]
Güncelleme için geçen süre:                                    1 saniye
date: geçersiz tarih `Ramazan'
Sabah vakti için bekleniyor... (19)
```

**date:** ile başlayan bölüm tekrarlanıyor. 

Uç birimden uygulama hiç başlamıyor.

Uygulama kısayol kullanarak çalıştı. 

Görünüşe göre vakitler yerine hicri takvimi getiriyor.

![image](https://user-images.githubusercontent.com/68565680/230920014-55256199-03b3-49d3-9ffc-b857e03ac54c.png)

Çalışmalarınızda başarılar.

Erdem

**Comment by fbostanci** [comment]
Teşekkür ederim Erdem Bey size de uygulama geliştirme yolunda başarılar. 

Sorun her zaman olduğu gibi diyanet sitesi kaynaklı. Hicri tarihleri ekleyince içerik sapıtmış :).

Güncel kodu yükledim. /usr/lib/ezanvakti/guncelleyici.bash dosyasında 245. satırda başlayan bölüm aşağıdaki şekilde güncellenecek. İsterseniz de güncel guncelleyici.bash dosyasını indirip sistemdeki ile değiştirebilirsiniz.

https://github.com/fbostanci/ezanvakti/blob/master/lib/guncelleyici.bash#L245
https://raw.githubusercontent.com/fbostanci/ezanvakti/master/lib/guncelleyici.bash

`printf '#Tarih       Sabah  Güneş  Öğle   İkindi Akşam  Yatsı\n' >> /tmp/ezanveri-$$
indirici "https://namazvakitleri.diyanet.gov.tr/tr-TR/${ilce_kodu}" | \
sed -n 's:<td>\(.*\)</td>:\1:p' | sed -e 's:^ *::' -e 's:[^[:print:]]: :g' -e \
's: Ocak :.01.:;s: Şubat :.02.:;
 s: Mart :.03.:;s: Nisan :.04.:;
 s: Mayıs :.05.:;s: Haziran :.06.:;
 s: Temmuz :.07.:;s: Ağustos :.08.:;
 s: Eyl&#252;l :.09.:;s: Ekim :.10.:;
 s: Kasım :.11.:;s: Aralık :.12.:'  \
 -e 's:[[:blank:]]*$::' -e '2~8d' >> /tmp/ezanveri-$$
sed -i -r '1!{s:\S+::2;}' /tmp/ezanveri-$$
sed -i '1!{N;N;N;N;N;N;s:\n:  :g}' /tmp/ezanveri-$$
`

**Comment by erdemoncel** [comment]
Önce yerel kod üzerinde **guncelleyici.bash** kütüğünün 245. satırını değiştirdim.

Bu yöntem başarılı olmayınca ezanvakti paketini kaldırdım, dizini de sildim.

Git kullanarak depoyu çektim.

`git clone https://github.com/fbostanci/ezanvakti.git `

**makepg -si** ile paketi tekrar kurdum.

Bir değişiklik olmadı.

Arch linux  paketinin [kaynak bölümü bu şekilde.](https://github.com/fbostanci/ezanvakti/blob/master/PKGBUILD#L15)

Üzerinde OpenBSD ve farklı farklı Linux işletim sistemleri barındıran bir diz üstü var.

Biraz önce Manjaro üzerinde aynı yöntemle sıfır kurulum yaptım. Sorun devam ediyor gibi gözüküyor.

Erdem

**Comment by fbostanci** [comment]
Merhaba Erdem Bey yaptığım denemelerde bir sorun gözükmüyordu. Yeniden denedim ve sorun oluşmadı. (Manjaro üzerinde)

Değişiklik yaptıktan sonra `ezanvakti --guncelle` ile ezanveri dosya içeriğinin güncellenmesi  ya da silinip tekrar ürettirmek gerekiyordu. Sildiğinize göre gerek kalmamış.

Depodaki PKGBUILD sürümü güncel değildi (7.2 için) . Az önce git sürümü için düzenleyip depoya yükledim. 
[Ezanvakti git sürümü PKGBUILD](https://raw.githubusercontent.com/fbostanci/ezanvakti/master/PKGBUILD)

Boş bir dizine indirip makepkg ile deneyin.
`rm ~/.config/ezanvakti/ezanveri` ile olası hatalı içeriği silip çalıştırın. Kolay gelsin.

**Comment by erdemoncel** [comment]
Şimdi sorun düzelmiş gözüküyor.

![image](https://user-images.githubusercontent.com/68565680/231876435-f0f01846-f866-47c9-b9ae-83943eb74219.png)

Allah'û Teâla ve Tekaddes Hazretleri (c.c) çalışmalarınızda kolaylıklar ihsân buyursun.

Erdem
